app_name = "hiper_solar"
app_title = "Hiper Solar"
app_publisher = "Hipersign Technologies"
app_description = "Solar installation lifecycle management for ERPNext"
app_email = "support@hipersignerp.com"
app_license = "mit"

required_apps = ["erpnext"]

# Without this the desk app-switcher builds an <img> with an undefined src
# and fires a 404 for /undefined on every page load.
app_logo_url = "/assets/hiper_solar/images/hiper_solar.svg"

# Installation
# ------------
after_install = "hiper_solar.install.after_install"
after_migrate = "hiper_solar.install.after_migrate"

# Doctypes the app owns end to end.
SOLAR_DOCTYPES = [
	"Solar Loan",
	"Site Visit",
	"Product Delivery",
	"Installation",
	"Paper Work",
	"Subsidy",
	"KSEB Office",
	"KSEB Paper Works",
	"Project Commission",
	"Solar Package Template",
]

# Standard doctypes the app extends.
EXTENDED_DOCTYPES = [
	"Customer",
	"Project",
	"Quotation",
	"Sales Order",
	"Serial No",
	"Stock Entry",
	"Issue",
	"Lead",
]

# Custom Fields are named explicitly. Filtering by `dt` alone would sweep in
# fields belonging to india_compliance, hrms and crm that sit on the same
# doctypes, and shipping those would fight with their owning apps.
SOLAR_CUSTOM_FIELDS = [
	"Customer-custom_work_stage",
	"Customer-custom_customer_work_stage",
	"Customer-custom_payment_summary",
	"Customer-custom_attachment_gallery",
	"Customer-custom_commissioning_checks",
	"Customer-custom_support_center",
	"Customer-custom_support_center_html",
	"Installation-material_tab",
	"Installation-site_warehouse",
	"Installation-return_warehouse",
	"Installation-material_status",
	"Installation-materials",
	"Installation-total_transferred_qty",
	"Installation-total_used_qty",
	"Installation-total_balance_qty",
	"Installation-consumption_stock_entry",
	"Installation-return_stock_entry",
	"Installation-custom_document_previews",
	"Installation-workflow_state",
	"Issue-workflow_state",
	"KSEB Paper Works-workflow_state",
	"Paper Work-workflow_state",
	"Product Delivery Item-batch_serial_section",
	"Product Delivery Item-has_serial_no",
	"Product Delivery Item-has_batch_no",
	"Product Delivery Item-is_stock_item",
	"Product Delivery Item-select_serial_batch",
	"Product Delivery Item-serial_batch_summary",
	"Product Delivery Item-batch_allocation",
	"Project-custom_miscellaneous_expense",
	"Project-custom_total_other_costs",
	"Project-custom_total_cost",
	"Project-custom_budget_remaining",
	"Project-custom_budget_used_percent",
	"Project Commission-commissioning_tab",
	"Project Commission-commissioning_checklist",
	"Project Commission-checks_summary",
	"Project Commission-test_results_section",
	"Project Commission-dc_voltage",
	"Project Commission-ac_voltage",
	"Project Commission-column_break_test_1",
	"Project Commission-earthing_resistance",
	"Project Commission-insulation_resistance",
	"Project Commission-column_break_test_2",
	"Project Commission-generation_at_test",
	"Project Commission-meter_reading",
	"Project Commission-inverter_serial_numbers",
	"Project Commission-acceptance_section",
	"Project Commission-tested_by",
	"Project Commission-customer_acceptance",
	"Project Commission-workflow_state",
	"Sales Order-site_visit",
	"Serial No-custom_project",
	"Serial No-custom_customer",
	"Serial No-custom_installation",
	"Serial No-custom_consumed_date",
	"Serial No-custom_warranty_period",
	"Serial No-custom_warranty_period_unit",
	"Serial No-custom_warranty_status",
	"Serial No-custom_amc_period",
	"Serial No-custom_amc_period_unit",
	"Serial No-custom_amc_start_date",
	"Serial No-custom_amc_status",
	"Solar Loan-workflow_state",
	"Stock Entry-installation",
	"Stock Entry-custom_projects",
	"Stock Entry-product_delivery",
	"Subsidy-workflow_state",
	"Lead-custom_kseb_phone_number",
	"Lead-custom_consumer_no",
	"Lead-custom_balance_feasibility",
	"Lead-custom_current_bill",
	"Lead-custom_kilo_watt__kw_",
	"Paper Work-custom_mnre",
	"Paper Work-custom_consumer_no",
	"Paper Work-custom_column_break_poaov",
	"Paper Work-custom_kseb_phone_number",
	"Paper Work-custom_current_bill",
	"Paper Work-custom_email",
	"Paper Work-custom_address",
	"Paper Work-custom_current_bill_image",
	"Lead-custom_current_bill_image",
	"Lead-custom_location_section",
	"Lead-custom_fetch_location",
	"Lead-custom_latitude",
	"Lead-custom_longitude",
	"Lead-custom_location_column",
	"Lead-custom_location_name",
	"Lead-custom_address",
	"Paper Work-custom_lead",
	"Paper Work-custom_mnre_location_section",
	"Paper Work-custom_latitude",
	"Paper Work-custom_longitude",
	"Paper Work-custom_location_column",
	"Paper Work-custom_location_name",
	"Customer-custom_lead_details_tab",
	"Customer-custom_consumer_no",
	"Customer-custom_kseb_phone_number",
	"Customer-custom_kilo_watt__kw_",
	"Customer-custom_balance_feasibility",
	"Customer-custom_lead_details_col",
	"Customer-custom_current_bill",
	"Customer-custom_current_bill_image",
	"Customer-custom_lead_location_section",
	"Customer-custom_latitude",
	"Customer-custom_longitude",
	"Customer-custom_lead_location_col",
	"Customer-custom_location_name",
	"Customer-custom_site_address",
	"Site Visit-custom_location_name",
	"Site Visit-custom_latitude",
	"Site Visit-custom_longitude",
	"Installation-custom_location_name",
	"Installation-custom_latitude",
	"Installation-custom_longitude",
	"Lead-custom_assigned_employee",
	"Lead-custom_assigned_employee_name",
	"Site Visit-custom_lead",
	"Site Visit-custom_lead_name",
	"Lead-custom_work_stage_tab",
	"Lead-custom_lead_work_stage",
	"Solar Loan-custom_lead",
	"Quotation-custom_lead",
	"Solar Loan-custom_documents",
	"Subsidy-custom_documents",
	"KSEB Paper Works-custom_documents",
	"Project Commission-custom_documents",
	"Paper Work-custom_documents",
	"Solar Loan-custom_other_documents",
	"Paper Work-custom_other_documents",
	"Subsidy-custom_other_documents",
	"KSEB Paper Works-custom_other_documents",
	"Project Commission-custom_other_documents",
	"Item-custom_solar_type",
	"Item-custom_item_capacity",
	"Quotation-custom_solar_section",
	"Quotation-custom_total_capacity",
	"Quotation-custom_col_solar_1",
	"Quotation-custom_roof_type",
	"Quotation-custom_col_solar_2",
	"Quotation-custom_solar_package",
	"Quotation Item-custom_solar_type",
	"Quotation Item-custom_item_capacity",
]

SOLAR_CLIENT_SCRIPTS = [
	"Customer Support Center",
	"Customer Payment Summary",
	"Customer Attachment Gallery",
	"Customer Work Stage Dashboard",
	"Customer Commissioning Checklist",
	"Installation - Create Paper Work",
	"Installation - Document Previews",
	"Installation - Material Consumption",
	"Installation - Total Project Cost Sync",
	"KSEB - Create Project Commission",
	"Paper Work - Create Subsidy and KSEB",
	"Product Delivery - Item Tracking Flags",
	"Product Delivery - Totals and Stock Transfer",
	"Project - Create Product Delivery",
	"Project - Total Cost Live Calculation",
	"Project Commission - Commissioning Checklist",
	"Quotation - Create Loan and Site Visit",
	"Sales Order - Trim Create Menu and Add Product Delivery",
	"Serial No - Warranty and Customer",
	"Site Visit - Create Sales Order",
	"Solar Loan - Create Site Visit",
	"Subsidy - Create KSEB",
	"Lead - Fetch Location",
	"Paper Work - Fetch from Lead",
	"Site Visit - Fetch from Lead",
	"Installation - Fetch from Lead",
	"Solar Loan - Fetch from Lead",
	"Product Delivery - Fetch from Lead",
	"Subsidy - Fetch from Lead",
	"KSEB Paper Works - Fetch from Lead",
	"Project Commission - Fetch from Lead",
	"Lead - Create Site Visit",
	"Lead Work Stage Dashboard",
	"Solar Package Template - Totals",
	"Quotation - Load Solar Package",
]

SOLAR_SERVER_SCRIPTS = [
	"Stock Entry - Stamp Serial Consumed Date",
	"Stock Entry - Update Installation Material",
	"Stock Entry - Revert Installation Material",
	"Stock Entry - Mark Product Delivery Transferred",
	"Stock Entry - Revert Product Delivery Transfer",
	"Serial No - Warranty Dates and Status",
	"Project - Total Cost and Budget",
	"Project Commission - Enforce Commissioning Evidence",
	"Lead - Get Place",
	"Lead - Get Details for Linked Docs",
	"Paper Work - Fill from Lead",
	"Site Visit - Link Lead and Customer",
	"Customer - Link Back to Lead Documents",
	"Quotation - Set Lead",
	"Solar Loan - Link Lead and Customer",
	"Installation - Fill from Lead",
	"Subsidy - Fill from Lead",
	"KSEB Paper Works - Fill from Lead",
	"Project Commission - Fill from Lead",
	"Product Delivery - Fill from Lead",
	"Solar Package Template - Totals",
]

SOLAR_WORKSPACES = [
	"Solar",
	"Solar Dashboard",
	"Solar Support",
	"Solar Support Dashboard",
]

fixtures = [
	{
		"dt": "Custom Field",
		"filters": [["name", "in", SOLAR_CUSTOM_FIELDS]],
	},
	{
		"dt": "Property Setter",
		"filters": [["doc_type", "in", SOLAR_DOCTYPES + EXTENDED_DOCTYPES]],
	},
	{
		"dt": "Client Script",
		"filters": [["name", "in", SOLAR_CLIENT_SCRIPTS]],
	},
	{
		"dt": "Server Script",
		"filters": [["name", "in", SOLAR_SERVER_SCRIPTS]],
	},
	{
		"dt": "Workflow",
		"filters": [["document_type", "in", SOLAR_DOCTYPES + ["Issue"]]],
	},
	{
		"dt": "Workflow State",
	},
	{
		"dt": "Workflow Action Master",
	},
	{
		"dt": "Custom HTML Block",
		"filters": [["name", "in", ["Solar Dashboard", "Customer Progress", "Support Dashboard"]]],
	},
	{
		"dt": "Workspace",
		"filters": [["name", "in", SOLAR_WORKSPACES]],
	},
	{
		"dt": "Workspace Sidebar",
		"filters": [["name", "in", ["Solar", "Solar Support"]]],
	},
	{
		"dt": "Print Format",
		"filters": [["name", "in", ["Quotation Swiss"]]],
	},
]
